### ISSUE TITLE
parrot-sphinx installation fails because of ulogger-dkms

### ISSUE THREAD

**Issue by pravardhanreddy** [Parrot-Developers/ulog#2]
I tried to install `parrot-sphinx` package following the instructions at https://developer.parrot.com/docs/sphinx/installation.html

The installation failed because of ulogger-dkms. So I removed them and tried installing ulogger-dkms on its own. Even that fails to install.
I get the following error in the terminal
```
ERROR (dkms apport): kernel package linux-headers-5.15.8-76051508-generic is not supported
Error! Bad return status for module build on kernel: 5.15.8-76051508-generic (amd64)
Consult /var/lib/dkms/ulogger/1.8/build/make.log for more information.
dpkg: error processing package ulogger-dkms (--configure):
 installed ulogger-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 ulogger-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I checked the `make.log` file and it had the following info
```
DKMS make.log for ulogger-1.8 for kernel 5.15.8-76051508-generic (amd64)
Fri 14 Jan 2022 12:23:24 PM EST
make: Entering directory '/usr/src/linux-headers-5.15.8-76051508-generic'
  CC [M]  /var/lib/dkms/ulogger/1.8/build/ulogger.o
In file included from /var/lib/dkms/ulogger/1.8/build/ulogger.c:5:
/var/lib/dkms/ulogger/1.8/build/ulogger-4.x.c: In function ‘ulogger_write_iter’:
/var/lib/dkms/ulogger/1.8/build/ulogger-4.x.c:52:15: error: ‘struct iov_iter’ has no member named ‘type’
   52 |  if (!((start).type & (ITER_BVEC | ITER_PIPE)))     \
      |               ^
/var/lib/dkms/ulogger/1.8/build/ulogger-4.x.c:668:2: note: in expansion of macro ‘iov_for_each’
  668 |  iov_for_each(iov, iter, *from) {
      |  ^~~~~~~~~~~~
/var/lib/dkms/ulogger/1.8/build/ulogger-4.x.c: In function ‘delete_log’:
/var/lib/dkms/ulogger/1.8/build/ulogger-4.x.c:1115:2: error: implicit declaration of function ‘rt_mutex_destroy’; did you mean ‘ww_mutex_destroy’? [-Werror=implicit-function-declaration]
 1115 |  rt_mutex_destroy(&current_log->mutex);
      |  ^~~~~~~~~~~~~~~~
      |  ww_mutex_destroy
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:277: /var/lib/dkms/ulogger/1.8/build/ulogger.o] Error 1
make: *** [Makefile:1874: /var/lib/dkms/ulogger/1.8/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.15.8-76051508-generic'
```
The other issue on this repo looks pretty similar to what i am facing.
This is my output of `uname -a`:
```
Linux pop-os 5.15.8-76051508-generic #202112141040~1639505278~20.04~0ede46a-Ubuntu SMP Fri Dec 17 19: x86_64 x86_64 x86_64 GNU/Linux
```

Please help on how to resolve this.

**Comment by JeromeBouvard** [comment]
pop-os ?

**Comment by pravardhanreddy** [comment]
Yes. It is based on Ubuntu 20.04 so shouldn't it work?

**Comment by JeromeBouvard** [comment]
No. The configuration to run sphinx is very strict.
